### ISSUE TITLE
Order in the requested data

### ISSUE THREAD

**Issue by sebascoca** [rbistolfi/cordoba_sounds#16]
We can differentiate two field, one for the personal data of the complainant (confidential data) and other for the report itself (public data). The first field must have all the data concerning the report, like this:

Datos sobre el reporte de ruido:
*Dirección de la fuente productora de ruido
*Ubicado entre las calles (opcional, creo)
*Barrio o localidad
*Tipo de ruido
*Grado de molestia
*Comentario
*Grabación de audio

Note that instead of using only "Dirección" and avoid confusion, replace it whit "Dirección de la fuente productora de ruido".
And the second field:

Datos personales del denunciante
*Nombre y apellido
*Email
*Teléfono (opcional)

**Comment by rbistolfi** [comment]
Fixed adding two <fieldsets>, one for personal data and one for noise data
