### ISSUE TITLE
Terminology

### ISSUE THREAD

**Issue by sebascoca** [rbistolfi/cordoba_sounds#6]
We must change some words for a better undestanding:
"Severidad" for "Grado de molestia"

Change the numerical rating for the following:
"Insoportable", "muy molesto", "molesto", "algo molesto", "poco molesto"

Because this project will be developed at Córdoba city, remove/comment this options (at least for this moment):
"Ciudad" and "Provincia"

The phone number must be optional, but I'm not sure about this.

**Comment by rbistolfi** [comment]
Hi Seba, 
I agree about this one. However, I think we should keep the numeric value for the database, and change it only in the form, so we can run functions on the data, such as average.

**Comment by sebascoca** [comment]
Hi Rodri,

You are right, for us this will be better to be numbers and not phrases.
