### ISSUE TITLE
Concordance between the map and address

### ISSUE THREAD

**Issue by sebascoca** [rbistolfi/cordoba_sounds#7]
Restrict the location at a specific area centered at Córdoba and put some clarification examples in the way the persons will write the names of the streets. For examples, if a look for "valparaiso 3000" this place is located at Villa María, and if a add "avenida" at the previous search a find the right place. The same happens whit "boulevard". 
We must recommend the complainant to be careful to set it to the correct location on the map and corresponding to the address entered, or otherwise use the map to take the data to be entered in the address field.
There some problems too whit the streets without numbers, for example "Haya de la torre s/n"

**Comment by sebascoca** [comment]
The problems of countless street is not our problem, it is the map itself (OSM and also google maps). Because the number is a requirement, in this cases any number is allowed. We must take care of this situation in the future.

**Comment by rbistolfi** [comment]
I agree. We will add a small legend with instructions, and also allow input via map as stated by issue #5

**Comment by sebascoca** [comment]
I was doing some tests and I think that we should add an optional field (or not) with the two streets among where is located the problem. This is because both OSM and google maps not always show the right direction that the user pointed out. Meanwhile we allow input via map, this would be a aceptable solution.

**Comment by rbistolfi** [comment]
This is fixed by #5. We allow position input via map now (double click) and I add a "entre calles" optional field.
