### ISSUE TITLE
Data confidentiality

### ISSUE THREAD

**Issue by sebascoca** [rbistolfi/cordoba_sounds#8]
We should clarify on the confidentiality of personal data entered in the form. Is must be written in the form.

**Comment by rbistolfi** [comment]
Hi Seba, I think we will need someone to redact this for us (I guess a lawyer is preferable), or we could check out what similar services are doing.

**Comment by sebascoca** [comment]
Ok Rodri, I will check for similar services at this instance, then we can consult a lawyer if necessary.

**Comment by sebascoca** [comment]
For this release we can put something short and concise like this:
"Todos los datos personales introducidos en el presente formulario no seran publicados bajo ninguna circunstancia ni dados a conocer a terceros"
